parameters:
#    blogblog.example.class: blog\blogBundle\Example

services:
#    blogblog.example:
#        class: %blogblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
