imperiv_gallery:
    resource: "@ImperivGalleryBundle/Controller/"
    type:     annotation
    prefix:   /

imperiv_site:
    resource: "@ImperivSiteBundle/Controller/"
    type:     annotation
    prefix:   /

