admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
imperiv_gallery:
    resource: "@ImperivGalleryBundle/Controller/"
    type:     annotation
    prefix:   /

imperiv_site:
    resource: "@ImperivSiteBundle/Controller/"
    type:     annotation
    prefix:   /

