services:
    sonata.admin.gallery_page:
        class: Imperiv\Bundle\GalleryBundle\Admin\GalleryPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Gallery pages" }
        arguments:
            - ~
            - Imperiv\Bundle\GalleryBundle\Entity\GalleryPage
            - ~
            
    sonata.admin.slide:
        class: Imperiv\Bundle\GalleryBundle\Admin\SlideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Gallery page slides" }
        arguments:
            - ~
            - Imperiv\Bundle\GalleryBundle\Entity\Slide
            - ~