services:
  sonata.media.provider.vimeo:
    class: Sonata\MediaBundle\Provider\VimeoProvider
    tags:
      - { name: sonata.media.provider }
    arguments:
      - sonata.media.provider.custom
      - @sonata.media.filesystem.local
      - @sonata.media.generator.default
      - @sonata.media.cdn.server
      - @sonata.media.thumbnail.format